class AllNews {
  final List<Autogenerated>? newsList;

  AllNews({this.newsList});

  factory AllNews.fromJson(List<dynamic> json) =>
      AllNews(newsList: json.map((e) => Autogenerated.fromJson(e)).toList());
}

class Autogenerated {
  int? id;
  int? date;
  FileNews? file;
  String? message;
  String? partialFileUrl;

  Autogenerated({this.id, this.date, this.file, this.message, this.partialFileUrl});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    date = json['date'];
    file = json['file'] != null ? FileNews.fromJson(json['file']) : null;
    message = json['message'];
    partialFileUrl = json['partialFileUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['date'] = date;
    if (file != null) {
      data['file'] = file!.toJson();
    }
    data['message'] = message;
    data['partialFileUrl'] = partialFileUrl;
    return data;
  }
}

class FileNews {
  String? id;
  String? name;
  String? mimeType;
  FileReference? fileReference;
  String? accessHash;
  int? size;

  FileNews({this.id, this.name, this.mimeType, this.fileReference, this.accessHash, this.size});

  FileNews.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    mimeType = json['mimeType'];
    fileReference = json['fileReference'] != null ? FileReference.fromJson(json['fileReference']) : null;
    accessHash = json['accessHash'];
    size = json['size'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['id'] = id;
    data['name'] = name;
    data['mimeType'] = mimeType;
    if (fileReference != null) {
      data['fileReference'] = fileReference!.toJson();
    }
    data['accessHash'] = accessHash;
    data['size'] = size;
    return data;
  }
}

class FileReference {
  String? type;
  List<int>? data;

  FileReference({this.type, this.data});

  FileReference.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    data = json['data'].cast<int>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = <String, dynamic>{};
    data['type'] = type;
    data['data'] = this.data;
    return data;
  }
}
