import 'dart:convert';

import 'package:dio/dio.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter_secure_storage/flutter_secure_storage.dart';
import 'package:kemsu_app/UI/views/news/test_model.dart';
import 'package:stacked/stacked.dart';
import 'package:http/http.dart' as http;
import '../../../API/config.dart';
import 'news_model.dart';

class NewsViewModelTest extends BaseViewModel {
  NewsViewModelTest(BuildContext context);
  final storage = const FlutterSecureStorage();
  List<NewsMessageClass> newsMessageList = [];
  List<NewsFileClass> newsFileList = [];
  List<Autogenerated> testModel = [];

  Future onReady() async {}

  void getMessages() async {
    String? token = await storage.read(key: 'tokenKey');
    Dio dio = Dio();
    // final response = await dio.get('${Config.newsMessagesTest}?limit=10',
    //     options: Options(headers: {'x-access-token': token}));
    final responseHttp = await http.get(
        Uri.parse('${Config.newsMessagesTest}?limit=10'),
        headers: {'x-access-token': token!});
    //var newsData = json.decode(responseHttp.body);
    // testModel = parseTest(json.decode(response.data[0]));
    print(responseHttp.body);
  }

  List<NewsMessageClass> parseNewsTextMessage(List response) {
    return response
        .map<NewsMessageClass>((json) => NewsMessageClass.fromJson(json))
        .toList();
  }

  List<NewsFileClass> parseFileMessage(List response) {
    return response
        .map<NewsFileClass>((json) => NewsFileClass.fromJson(json))
        .toList();
  }

  List<Autogenerated> parseTest(List response) {
    return response
        .map<Autogenerated>((json) => Autogenerated.fromJson(json))
        .toList();
  }
}
