class AllNews {
  final List<Autogenerated>? newsList;

  AllNews({this.newsList});

  factory AllNews.fromJson(List<dynamic> json) =>
      AllNews(newsList: json.map((e) => Autogenerated.fromJson(e)).toList());
}

class Autogenerated {
  int? id;
  int? date;
  FileNews? file;
  String? message;
  String? partialFileUrl;

  Autogenerated(
      {this.id, this.date, this.file, this.message, this.partialFileUrl});

  Autogenerated.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    date = json['date'];
    file = json['file'] != null ? new FileNews.fromJson(json['file']) : null;
    message = json['message'];
    partialFileUrl = json['partialFileUrl'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['date'] = this.date;
    if (this.file != null) {
      data['file'] = this.file!.toJson();
    }
    data['message'] = this.message;
    data['partialFileUrl'] = this.partialFileUrl;
    return data;
  }
}

class FileNews {
  String? id;
  String? name;
  String? mimeType;
  FileReference? fileReference;
  String? accessHash;
  int? size;
  Null? thumbs;

  FileNews(
      {this.id,
      this.name,
      this.mimeType,
      this.fileReference,
      this.accessHash,
      this.size,
      this.thumbs});

  FileNews.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    name = json['name'];
    mimeType = json['mimeType'];
    fileReference = json['fileReference'] != null
        ? new FileReference.fromJson(json['fileReference'])
        : null;
    accessHash = json['accessHash'];
    size = json['size'];
    thumbs = json['thumbs'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['name'] = this.name;
    data['mimeType'] = this.mimeType;
    if (this.fileReference != null) {
      data['fileReference'] = this.fileReference!.toJson();
    }
    data['accessHash'] = this.accessHash;
    data['size'] = this.size;
    data['thumbs'] = this.thumbs;
    return data;
  }
}

class FileReference {
  String? type;
  List<int>? data;

  FileReference({this.type, this.data});

  FileReference.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    data = json['data'].cast<int>();
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['data'] = this.data;
    return data;
  }
}
