name: kemsu_app
description: A new Flutter project.

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^2.3.0
  mask_text_input_formatter: ^2.1.0
  flutter_svg: ^1.0.3
  dio: ^4.0.4
  flutter_secure_storage: ^5.0.2
  http: ^0.13.4
  json_annotation: ^4.7.0
  url_launcher: ^6.1.2
  file_picker: ^4.6.0
  open_file: ^3.2.1
  flutter_typeahead: ^4.0.0
  html: ^0.15.0
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  webview_flutter: ^3.0.4
  translit: ^2.0.0
  image_picker: ^0.8.6
  path_provider: ^2.0.11
  intl: ^0.17.0
  dropdown_search: ^5.0.3
  flutter_launcher_icons: ^0.11.0
  shared_preferences: ^2.0.15
  audioplayers: ^2.0.0
  video_player: ^2.4.10
  appmetrica_plugin: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  freezed: ^2.2.0
  json_serializable: ^6.5.3

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - assets/


flutter_icons:
  image_path: "assets/icon/icon.png"
  android: true
  ios: true