name: kemsu_app
description: A new Flutter project.

publish_to: 'none'
version: 2.8.0+23

environment:
  sdk: ">=2.17.0-69.2.beta <3.18.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.2
  mask_text_input_formatter: ^2.9.0
  flutter_svg: ^2.0.10+1
  dio: ^5.4.2+1
  flutter_secure_storage: ^9.0.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  url_launcher: ^6.2.5
  file_picker: ^8.0.0+1
  open_file: ^3.3.2
  flutter_typeahead: ^5.2.0
  html: ^0.15.4
  cupertino_icons: ^1.0.6
  webview_flutter: ^4.7.0
  translit: ^2.0.1
  image_picker: ^1.0.7
  intl: ^0.19.0
  dropdown_search: ^5.0.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  audioplayers: ^6.0.0
  video_player: ^2.8.5
  appmetrica_plugin: ^1.4.0
  photo_view: ^0.14.0
  socket_io_client: ^2.0.3+1
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5
  get_it: ^7.6.8
  flutter_local_notifications: ^17.0.0
  badges: ^3.1.2
  package_info_plus: ^7.0.0
  flutter_pw_validator: ^1.6.0
  provider: ^6.1.2
  flutter_polls: ^0.1.6
  uuid: ^4.4.0
  permission_handler: ^11.3.1
  in_app_review: ^2.0.9
  go_router: ^13.2.3
  youtube_player_flutter: ^9.0.0
  device_info_plus:
  firebase_core: ^2.30.1
  firebase_messaging: ^14.9.1
  firebase_analytics: ^10.10.4

dev_dependencies :
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  flutter_lints: ^3.0.2
  freezed: ^2.5.1
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - assets/
    - assets/icon/
    - assets/preloaded/


flutter_icons:
  image_path: "assets/icon/icon4.png"
  android: true
  ios: true