name: kemsu_app
description: A new Flutter project.

publish_to: 'none'
version: 2.0.5+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.1+1
  mask_text_input_formatter: ^2.5.0
  flutter_svg: ^2.0.9
  dio: ^5.3.3
  flutter_secure_storage: ^9.0.0
  http: ^1.1.0
  json_annotation: ^4.8.1
  url_launcher: ^6.2.1
  file_picker: ^6.0.0
  open_file: ^3.3.2
  flutter_typeahead: ^4.8.0
  html: ^0.15.4
  cupertino_icons: ^1.0.6
  freezed_annotation: ^2.4.1
  webview_flutter: ^3.0.4
  translit: ^2.0.1
  image_picker: ^1.0.4
  path_provider: ^2.1.1
  intl: ^0.18.1
  dropdown_search: ^5.0.6
  flutter_launcher_icons: ^0.13.1
  shared_preferences: ^2.2.2
  audioplayers: ^5.2.0
  video_player: ^2.8.1
  chewie: ^1.7.1
  appmetrica_plugin: ^1.4.0
  photo_view: ^0.14.0
  socket_io_client: ^2.0.3+1
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  get_it: ^7.6.4
  flutter_local_notifications: ^12.0.2
  badges: ^3.1.2
  package_info_plus: ^4.2.0
  flutter_pw_validator: ^1.6.0
  provider: ^6.0.5
  flutter_polls: ^0.1.5
  uuid: ^4.2.1
  permission_handler: ^11.0.1
  in_app_review: ^2.0.8
  go_router: ^12.1.1
  animated_splash_screen: ^1.3.0
  device_info_plus:

dev_dependencies :
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.6
  flutter_lints: ^3.0.0
  freezed: ^2.4.5
  json_serializable: ^6.7.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - images/icons/
    - assets/
    - assets/icon/


flutter_icons:
  image_path: "assets/icon/icon4.png"
  android: true
  ios: true